### PR TITLE
Addition of l10n

### PR DESCRIPTION
**Pull request by Valdnet**
Adding a translation in Polish for "Additional settings" in the Nextcloud instance administrator settings.

### CODE REVIEW

**Comment by pierre-alain-b** [comment]
Excellent, I will take this into account!

**Comment by pierre-alain-b** [comment]
I shall review the change in the PHP file.
I will then validate the new localized version.

**Comment by Valdnet** [comment]
> 
> 
> I shall review the change in the PHP file.
> I will then validate the new localized version.

OK.
I test it on my Nextcloud and it works very well 😉.

**Comment by pierre-alain-b** [comment]
what is the intent of the php file change?

**Comment by Valdnet** [comment]
> 
> 
> what is the intent of the php file change?

1. Center the description to checkbox.
2. Delete duplicate `id="rainloop-autologin"` in the checkbox.

**Pull request merged**
