### PR TITLE
Updates app to use NextCloud's App Framework

### PR DESCRIPTION
**Pull request by nkinkade**
@pierre-alain-b, @tabp0le: This PR supersedes #75 in that it is built on top of already-merged PR #74 (now master). This should bring in the relevant changes from #74, as well as additional improvements, and can be cleanly merged.

This biggest thing this PR does is to integrate the Nextcloud App Framework, to the extent I was able. No doubt there is room for improvement, but this should be a good start.  I've tested these changes on my own server and things seem to work fine.

The one thing I could use help with is understanding when the (now removed) files `ajax/admin.php` and ajax/personal.php` were used so that I can so some testing to be sure that [their replacements (in lib/Controller/AjaxController.php)](https://github.com/nkinkade/rainloop-nextcloud/blob/appframework-nc14/rainloop/lib/Controller/AjaxController.php) actually work as intended.

I also removed a number of files that I wasn't sure were even needed any longer. Things seem to work fine without them, but maybe I got overzealous with removing them?

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by nkinkade** [comment]
@pierre-alain-b: Just checking in on this PR to see if there is anything I can do to be help with this? The code as represented by this PR has been running on my server a month or so now with no apparent problems or issues. Let me know...  Thanks!

**Comment by pierre-alain-b** [comment]
Sorry, I have not yet taken the time to review it thoroughly. Clearly it seems interesting to go to 6.1 with your version. I will try to find some time to review in the coming days.

**Comment by tabp0le** [comment]
Yeah, I'm sorry I haven't had a chance to either. I'll try to get some time and test as well.

**Comment by nkinkade** [comment]
Thank you both.  As I was upgrading to NC 14.0.3 last week I discovered a small problem with info.xml. It seems the change I pushed now is causing conflicts for merging this PR. They are very small conflicts, but I'll try to resolve them to make it so that this PR can cleanly merge.

**Comment by nkinkade** [comment]
@pierre-alain-b: Thanks you for continuing to maintain this Rainloop NC integration. This PR was really old, but I'm curious why you closed it?

**Comment by pierre-alain-b** [comment]
I assumed it was no longer needed but I may very well be wrong. What are the benefits of this PR compared to the changes we made earlier in Oct 2018?

**Comment by nkinkade** [comment]
The changes made by @tabp0le 1.5 yeas ago, as I understood it at the time, were mostly just workarounds to keep the Rainloop app working at all with NC. The changes in this PR were a first attempt at migrating the entire Rainloop app (to the extent that I was able) to the Nextcloud App Framework. It's been 1.5 years now, but my understanding is that some parts of the current Rainloop app are using deprecated ways of doing things that could be removed at some point, or at the very least are not following NC app development best-practices.

Looking back at my initial PR comment, I see that it got a thumbs-up from @MorrisJobke who I believe may be on the core Nextcloud development team. I also noticed that 3 or 4 weeks ago @kesselb made [a comment in a separate issue](https://github.com/nextcloud/server/issues/18865#issuecomment-574403997) which pointed at this PR noting:

> This method to register a admin or personal page is deprecated since Nextcloud 14. It will be removed at some point in the future. If you like the rainloop app probably try to migrate some of the code? pierre-alain-b/rainloop-nextcloud#76 looks like a start.

Looking at the conflicting files list, it's clear that my changes from 1.5 years ago will need some revision and updating. But my general impression is that this PR (cleaned up) would make a good initial step in the direction of bringing the Rainloop app code more up to speed with recommended NC app development standards, namely using the App Framework.

I don't have a ton of time these days (two small boys, full-time job, etc.), but if others think that the intent of this PR would still be a step in the right direction for this app, then I can perhaps try to find some time in the next month or two to bring this PR up to date.

**Comment by tabp0le** [comment]
> 
> 
> The changes made by @tabp0le 1.5 yeas ago, as I understood it at the time, were mostly just workarounds to keep the Rainloop app working at all with NC. The changes in this PR were a first attempt at migrating the entire Rainloop app (to the extent that I was able) to the Nextcloud App Framework. It's been 1.5 years now, but my understanding is that some parts of the current Rainloop app are using deprecated ways of doing things that could be removed at some point, or at the very least are not following NC app development best-practices.
> 
> Looking back at my initial PR comment, I see that it got a thumbs-up from @MorrisJobke who I believe may be on the core Nextcloud development team. I also noticed that 3 or 4 weeks ago @kesselb made [a comment in a separate issue](https://github.com/nextcloud/server/issues/18865#issuecomment-574403997) which pointed at this PR noting:
> 
> > This method to register a admin or personal page is deprecated since Nextcloud 14. It will be removed at some point in the future. If you like the rainloop app probably try to migrate some of the code? #76 looks like a start.
> 
> Looking at the conflicting files list, it's clear that my changes from 1.5 years ago will need some revision and updating. But my general impression is that this PR (cleaned up) would make a good initial step in the direction of bringing the Rainloop app code more up to speed with recommended NC app development standards, namely using the App Framework.
> 
> I don't have a ton of time these days (two small boys, full-time job, etc.), but if others think that the intent of this PR would still be a step in the right direction for this app, then I can perhaps try to find some time in the next month or two to bring this PR up to date.

Jeeze, it's been so long I don't even remember the exact situation. Maybe someone can check out the PR, re-base and resubmit? I'd do it, but I don't have the time either right now.

**Comment by nkinkade** [comment]
@pierre-alain-b: I've rebased the old branch of this PR onto master of this repo, which removed all the conflicts. I haven't tested this extensively, but I checked out the branch that this PR is based on and symlinked `nextcloud/apps/rainloop` to it, and so far things seem to work fine. Granted, I probably don't use every feature of Rainloop. In any case, I think this PR is ready for reevaluation. 

My understanding is that one of the original impediments to merging this PR was that you didn't have sufficient time to be sure that the PR didn't introduce regressions of any sort, or new breakages, which is completely understandable (I'm in the same boat). For this reason, I'm hoping that we can get folks like @tabp0le  or whoever else is very reliant on this app to do some (at least) minimal testing of this PR to be sure that it doesn't break functionality for others.  Like I say, all the things I rely on seem to work just fine now, as they did around 1.5 years ago.

I'd love to see this PR merged and a new release tagged, since I rely heavily on this app (thank you, again) and want to see it continue working with Nextcloud into the future without constant one-off tweaking to keep deprecated practices working with later versions of Nextcloud.

**Comment by pierre-alain-b** [comment]
Thank you so much, I will test this myself and I invite everyone motivated to test it as well.

**Comment by nextgen-networks** [comment]
> Thank you so much, I will test this myself and I invite everyone motivated to test it as well.

I'll try to take that snapshot and give it a shot in my docker test env until the end of that week.
Will post results here when finished.

**Comment by nkinkade** [comment]
Thank you. For what it's worth, I used the version from this PR for several days in my own NC install and did not encounter any issues.

**Comment by nkinkade** [comment]
Just touching base on this PR. There is no rush on this, necessarily, but I just want to try to ensure that it doesn't slip through the cracks again. The longer the PR goes without attention, and the more other changes that are merged to master, the more work is possibly involved in rebasing this PR onto master again.

My belief is that this PR takes the NC Rainloop app in the right direction for best practices and compatibility with future NC releases.

**Comment by pierre-alain-b** [comment]
I am just a little bit concerned by the changes in Rainloop itself: rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Providers/Suggestions/OwnCloudSuggestions.php
These changes will have to be backporter to each update of Rainloop itself, it is feasible of course but less transparent. But, well, I understand this is needed.

**Comment by pierre-alain-b** [comment]
The updated app does not work on my instance.
Nothing in the nextcloud log.
But I get this error message in the browser console:
`Content Security Policy: The page’s settings blocked the loading of a resource at https://url.tld/index.php/apps/rainloop/app/?OwnCloudAuth (“default-src”).`

Any idea?

**Comment by nkinkade** [comment]
@pierre-alain-b:
* Regarding the change to a core RainLoop file, your concern is valid and makes sense. Any possibility of getting the change implemented upstream? It looks like [the file in the RainLoop source](https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/app/libraries/RainLoop/Providers/Suggestions/OwnCloudSuggestions.php) hasn't been touched for nearly 4 years.
* For the CSP error, can I assume that `url.tld` is just a redaction you made for privacy? Assuming so, is your webserver configured to send some specific CSP header that might be restricting loading of the script? Or is the URL perhaps pointing to some other server?

**Comment by pierre-alain-b** [comment]
- I agree that the change could be proposed upstream but I am afraid that it will collide with the work done to maintain the owncloud plugin (not sure how much it is used that said)
- For the CSP error, indeed I redacted the URL for privacy purpose. I have no special CSP setting and the url is the url of the nextcloud server with no surprise... I will do more tests.

**Comment by nkinkade** [comment]
I can see how modifying and upstream file is less than ideal. I just pushed a commit to my branch that removes the changes to `OwnCloudSuggestions.php`. I tested the change on my server, and everything seemed to work fine. If I recall, there was some `occ` command I had run to find all deprecated calls, or something along those lines, and it probably picked that one up and I made the change. But since that file is not actually part of the Nextcloud integration, and the first condition will almost always be met on modern installs, then leaving that old `elseif` in place seems fine.

For what it's worth, here's how I'm testing this on my own server:
1. Disable Rainloop app in my instance.
2. [git-clone my fork of your repo](https://github.com/nkinkade/rainloop-nextcloud.git) into the root of my Nextcloud install.
3. git-checkout the branch `appframework-nc14`
4. Move existing `apps/rainloop` app directory anywhere else, like `/tmp/rainloop.dist`.
5. `$ cd apps && ln -s ../rainloop-nextcloud/rainloop`
6. Re-enable the Rainloop app in Nextcloud
7. Experiment and test functionality.

**Comment by pierre-alain-b** [comment]
The routes file has just been updated to fix an issue with NC 19 beta. The construction of routes is pretty much different. Should we alter the new routes file somehow?

**Comment by nkinkade** [comment]
I'm not sure I understand the change in #151. My understanding is that the [routes are supposed to be relative to the app's root](https://docs.nextcloud.com/server/latest/developer_manual/app/tutorial.html#routes-controllers), not the root of Nextcloud.

It wouldn't surprise me if that change actually working has something to do with the fact that this app is not currently utilizing the App Framework. I would be curious to have someone test my PR on 19 Beta to see if it has the same issue.

What is currently blocking this PR (notwithstanding the conflicting change that was just added by #151 in routes.php)? Is it just that you weren't able to successfully get a version based on this PR working in your testing environment?

I believe this PR is quite important, and will only become more important over time.

I'm happy to help push this PR through however I can. Let me know how I can help.

Thanks!

**Comment by pierre-alain-b** [comment]
Well I have tried to use the version with the merged PR but it fails to load... again...

**Comment by pierre-alain-b** [comment]
Same behavior. Nothing in the nextcloud log.
But I get this error message in the browser console:
Content Security Policy: The page’s settings blocked the loading of a resource at https://url.tld/index.php/apps/rainloop/app/?OwnCloudAuth (“default-src”).

Any idea?

**Comment by pierre-alain-b** [comment]
In Chromium, the error message is similar: "refused to frame 'https://url.tld/index.php/apps/rainloop/app/?OwnCloudAuth' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback."

**Comment by pierre-alain-b** [comment]
It is presumably because this line was removed as not compatible with the new framework:
`./apps/rainloop/app.php:$policy = 'default-src \'self\'; '`

**Comment by pierre-alain-b** [comment]
OK i think we can move in that direction: https://docs.nextcloud.com/server/15/developer_manual/app/requests/controllers.html?highlight=content%20security%20policy 

`
addAllowedFrameDomain (string $domain)
`

**Comment by pierre-alain-b** [comment]
OK I get it to work by adding:
```
                $csp = new ContentSecurityPolicy();
                $csp->addAllowedFrameDomain("'self'");
                $response->setContentSecurityPolicy($csp);
```

**Comment by pierre-alain-b** [comment]
Does it seem correct to you?

**Comment by pierre-alain-b** [comment]
Also, after the update, I do not find the admin settings for rainloop

**Comment by pierre-alain-b** [comment]
And I have the feeling that it is needed to reset the storage of the app and reconfigure the app. Right ?

**Comment by pierre-alain-b** [comment]
And the last point seems very annoying for users as they will have issues using the app after update.

**Comment by nkinkade** [comment]
@pierre-alain-b: I'm sorry for the late reply here. I'm UTC-6 and am just now seeing these message. I'm sorry you ran into so many problems. I'm not sure why I didn't run into the same issues when I was testing this. A couple of comments/questions:
* Thank you for debugging that CSP issue. It looks like you found a workable solution.
* Were you able to test the `routes.php` from my PR (unmodified) with NC 19 Beta? Did it  work, or did it require the same change as in #151?
* Were you able to resolve the issue accessing the admin panel? In my testing I didn't have any issues accessing the admin panel.

**Comment by pierre-alain-b** [comment]
I have not been able to make the admin panel visible in the admin settings of Nextcloud. Do you have that?

**Comment by nkinkade** [comment]
I just [submitted a new PR](https://github.com/pierre-alain-b/rainloop-nextcloud/pull/156) which should fix the CSP and admin-settings issues. Additionally, it restores the personal-settings, which aren't even present in the currently release of this app, as far as I can tell. Not sure if those going away was intentional due  to the security concerns of storing email/password in the NC database, but this bring it back with a note of caution.

To test these changes I created a completely fresh install of NC 19 Beta2 on my server and checked out the rainloop app from my fork with branch `appframework-nc14`, then made changes to that branch. That is, these changes should be compatible with NC 19. And it turns out the changes to routes.php introduced in #151 appear to not be necessary.

**Pull request merged**
