### PR TITLE
Re-enables auto-logins with NC email instead of username 

### PR DESCRIPTION
**Pull request by nkinkade**
This PR ports forward the option to allow users to auto-login to RainLoop using their NC email (instead of NC username). It also updates the text for each option to make it clearer (to me at least) what each options does. l10n files were also update with new strings.

Other changes:
* Copies favicon from the RainLoop app itself so that the browser tab for this app shows the RainLoop icon instead of the NC one.
* Moves the unread inbox message count to the left of "Email" in the tab for those of us who have a bazillion tabs open and they are all very small, making the unread message count invisible because tab is so small. This may help that a little.
* Removes the file `/admin.php`. It is no longer used or needed. It's functionality is now replaced with `lib/Settings/AdminSettings.php`.

### CODE REVIEW

**Comment by piti-diablotin** [comment]
Looks good to me :smile:

**Comment by pierre-alain-b** [comment]
Thank you, looks good indeed!

**Comment by pierre-alain-b** [comment]
I've published 7.0-beta-5 with the modifications merged.

**Comment by Valdnet** [comment]
@nkinkade Good job 👍.
@pierre-alain-b The French translation needs to be improved 😉.

I will translate Polish and Russian.

**Pull request merged**
