### PR TITLE
Gets admin and personal settings working again

### PR DESCRIPTION
**Pull request by nkinkade**
These changes should remove the Content Security Policy issues on loading the main page, as well as restore RainLoop options under Settings->Admin->Additional Settings.

Additionally, I noticed that even under the current release of this app that Settings->Personal->Additional Settings was broken/missing. This PR should restore that functionality, but adding a word of caution.

### CODE REVIEW

**Comment by nkinkade** [comment]
NOTE: This PR is entering into somewhat uncharted territory for me with regard to git/GitHub interaction. At some point you merged your master branch into my fork's `appframework-nc14` branch. I didn't even know this was possible until I [read in the docs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks) today that it is:

> When you make changes in your user-owned fork and open a pull request that compares your work to the upstream repository, you can give anyone with push access to the upstream repository permission to push changes to your pull request branch.

Then you merged my previous PR #76 (including your merge of master into the PR), but then later [reverted the merge](https://github.com/pierre-alain-b/rainloop-nextcloud/commit/867fcb5cca8480440606d21f07590e406dc2c9c7) commit. My expectation upon creating this new PR against your master branch was that it would include all of the changes from my previous PR #76, as well as my fixes for CSP and settings. But in fact it only apparently contains the fixes for CSP and settings. I'm confused by this, and it may be that I'm not fully understanding how git works, or how Github works, or both. 

In any case, I see this PR has all sorts of conflicts. Let me know if I need to resubmit a PR in some other format or on some other branch, etc.

**Comment by pierre-alain-b** [comment]
No you understand very well how it works.
I did revert because I want to ship a version 6.1.1 with a few fixes and restart the work from your PR to build a 7.0.
The main issue I see now, after what you have done, is potentially the loss of data for users. On my instance, I lost all previous settings when deploying 7.0-beta with your initial PR. I am not sure why this happened but clearly I cannot release an update like this without being as positive as I can that this will not be the case for all other users because they will not expect that an automatic update could break that.

**Comment by pierre-alain-b** [comment]
So thank you very much for your work and I will try to incorporate all this as quickly as feasible but garanteeing the best outcome for users!

**Comment by nkinkade** [comment]
Understood. Please don't hesitate to let me know if you have any questions or concerns about these new changes, or if I can modify this PR in any way to help make your life easier, or if I can help with testing in some way. As I mentioned, I have all of this running on a clean install of Nextcloud 19 Beta2 on my server. Since it was a clean install, I wasn't able to verify whether these changes overwrite exiting app settings, but I'm not sure why they would. Thanks.

**Comment by pierre-alain-b** [comment]
OK I pushed 6.1.1 and I hope that this will be the latest release not incorporating your nice refactoring. So, if I want to make things right, I need to apply both the previous PR and this PR, correct?

**Comment by nkinkade** [comment]
I believe that is correct, though as I mentioned, I'm a little confused by what happened. There is clearly something I'm not understanding about git/Github. I expected this PR to contain everything, since it is being applied to your master branch, which reverted the earlier PR. But my confusion aside, based on what this PR shows, I would say you may be right, that it will be necessary to un-revert my  previous PR and merge this PR too, somehow.

Please let me know if I can help in any way. Thanks again for maintaining this App!

**Pull request merged**
